pipeline {
    agent any

    stages {
        stage('Run mvn package') {
        
            steps {
                dir('sbom') {
                   sh 'mvn package'
                }
            }
        }

        stage('dependencyTrackPublisher') {
            steps {
                dependencyTrackPublisher artifact: 'sbom/target/bom.json', projectId: '443757ec-375c-449f-9ad6-f98c4907a05c', synchronous: true
            }
        }
    }
}
