pipeline {
    agent any

    stages {
        stage('Run mvn package') {
        
            steps {
                dir('sbom') {
                   sh 'mvn package'
                }
            }
        }

        stage('dependencyTrackPublisher') {
            steps {
                dependencyTrackPublisher artifact: 'sbom/target/bom.xml', projectId: '2bf87da1-b7b7-4679-92e4-81a289901a3d', synchronous: true
            }
        }
    }
}
