pipeline {
    agent any

    stages {
        stage('Run mvn package') {
            steps {
                sh 'mvn package'
            }
        }

        stage('dependencyTrackPublisher') {
            steps {
                dependencyTrackPublisher artifact: 'target/bom.xml', projectId: '6807c5e0-9e6a-4698-85b8-51ce24a49c21', synchronous: true
            }
        }
    }
}
