services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "443:443"
        networks:
            - tls_basic

    backend:
        image: python:3.9-slim
        command: python -m http.server 5000
        networks:
            - tls_basic

networks:
    tls_basic:
        driver: bridge
