services:
    keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:26.0.5
      command: start-dev
      environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/postgres
        KC_DB_USERNAME: postgres
        KC_DB_PASSWORD: postgres
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        KC_METRICS_ENABLED: "true"
        KC_HEALTH_ENABLED: "true"
        KC_PROXY_HEADERS: xforwarded
        KC_LOG_CONSOLE_LEVEL: info
      ports:
        - 8080:8080
    postgres:
       image: postgres:15.3
       environment:
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=postgres
       ports:
           - "5432:5432"
