services:
    keycloak:
        image: quay.io/keycloak/keycloak:26.0.5
        environment:
            - KC_BOOTSTRAP_ADMIN_USERNAME=admin
            - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
            - KC_HEALTH_ENABLED=true
            - KC_LOG_LEVEL=INFO
            - KC_DB=postgres
            - KC_DB_PASSWORD=postgres
            - KC_DB_USERNAME=postgres
        command: start --http-port 8082
        ports:
            - "8082:8082"
            - "9000:9000"
        depends_on:
            - postgres

#    spring-app:
#        build:
#            context: .
#        ports:
#            - "8080:8080"
#        environment:
#            - SPRING_PROFILES_ACTIVE=default
#        depends_on:
#            - keycloak

    postgres:
        image: postgres:15.3
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
