services:
    nginx_server:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./certs/server.crt:/etc/nginx/ssl/server.crt
            - ./certs/server.key:/etc/nginx/ssl/server.key
            - ./certs/ca.crt:/etc/nginx/ssl/ca.crt
        ports:
            - "443:443"
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
